IF object_id('HISTORIAL_CLINICO_RANGO_MOVIMIENTO_EXAMEN_FISICO') IS NOT NULL DROP TABLE HISTORIAL_CLINICO_RANGO_MOVIMIENTO_EXAMEN_FISICO;
CREATE TABLE HISTORIAL_CLINICO_RANGO_MOVIMIENTO_EXAMEN_FISICO(
	HIST_ID INT NOT NULL,
	HIST_fecha_registro DATE NOT NULL,
	HIST_registro INT NOT NULL,
	HIST_codigo INT NOT NULL,

	HIST_RMEF_ID INT IDENTITY(1,1),

	HIST_acti_cadera_ext_derecha VARCHAR(50) NOT NULL,
	HIST_acti_cadera_ext_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_cadera_ext_contractura VARCHAR(50) NOT NULL,
	HIST_acti_cadera_flex_derecha VARCHAR(50) NOT NULL,
	HIST_acti_cadera_flex_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_cadera_flex_contractura VARCHAR(50) NOT NULL,
	HIST_acti_cadera_add_derecha VARCHAR(50) NOT NULL,
	HIST_acti_cadera_add_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_cadera_add_contractura VARCHAR(50) NOT NULL,
	HIST_acti_cadera_abd_derecha VARCHAR(50) NOT NULL,
	HIST_acti_cadera_abd_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_cadera_abd_contractura VARCHAR(50) NOT NULL,
	HIST_acti_cadera_r_int_derecha VARCHAR(50) NOT NULL,
	HIST_acti_cadera_r_int_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_cadera_r_int_contractura VARCHAR(50) NOT NULL,
	HIST_acti_cadera_r_ext_derecha VARCHAR(50) NOT NULL,
	HIST_acti_cadera_r_ext_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_cadera_r_ext_contractura VARCHAR(50) NOT NULL,
	HIST_acti_rodilla_ext_derecha VARCHAR(50) NOT NULL,
	HIST_acti_rodilla_ext_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_rodilla_ext_contractura VARCHAR(50) NOT NULL,
	HIST_acti_rodilla_flex_derecha VARCHAR(50) NOT NULL,
	HIST_acti_rodilla_flex_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_rodilla_flex_contractura VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_dorsi_derecha VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_dorsi_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_dorsi_contractura VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_planta_derecha VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_planta_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_planta_contractura VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_inver_derecha VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_inver_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_inver_contractura VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_ever_derecha VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_ever_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_tobillo_ever_contractura VARCHAR(50) NOT NULL,
	HIST_acti_flex_ext_pie_derecha VARCHAR(50) NOT NULL,
	HIST_acti_flex_ext_pie_izquierda VARCHAR(50) NOT NULL,
	HIST_acti_flex_ext_pie_contractura VARCHAR(50) NOT NULL,

	HIST_pasi_cadera_ext_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_ext_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_ext_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_flex_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_flex_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_flex_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_add_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_add_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_add_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_abd_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_abd_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_abd_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_r_int_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_r_int_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_r_int_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_r_ext_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_r_ext_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_cadera_r_ext_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_rodilla_ext_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_rodilla_ext_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_rodilla_ext_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_rodilla_flex_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_rodilla_flex_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_rodilla_flex_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_dorsi_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_dorsi_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_dorsi_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_planta_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_planta_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_planta_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_inver_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_inver_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_inver_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_ever_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_ever_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_tobillo_ever_contractura VARCHAR(50) NOT NULL,
	HIST_pasi_flex_ext_pie_derecha VARCHAR(50) NOT NULL,
	HIST_pasi_flex_ext_pie_izquierda VARCHAR(50) NOT NULL,
	HIST_pasi_flex_ext_pie_contractura VARCHAR(50) NOT NULL
);

ALTER TABLE HISTORIAL_CLINICO_RANGO_MOVIMIENTO_EXAMEN_FISICO ADD CONSTRAINT PK_HISTORIAL_CLINICO_RANGO_MOVIMIENTO_EXAMEN_FISICO PRIMARY KEY (HIST_RMEF_ID);
